//LOCALHOST

### Get All contact
GET http://localhost:8080/contacts

### Get One contact by id
GET http://localhost:8080/contacts/69087dae58cdd8c50f19938c


// PRODUCTION
### Get All contacts
GET https://cse341-contacts-vs3z.onrender.com/contacts

### Get One contact by id
GET https://cse341-contacts-vs3z.onrender.com/contacts/69087bd558cdd8c50f19938a